### PR TITLE
Update template variable replacement logic to use search query string

### PR DESCRIPTION
**Pull request by huskerdhf**
### Overview

The purpose of this change is to fix how the logs plugin does the template variable replacement which was not working in that any template variables referenced in the search query string were not being replaced.

The changes were tested to support the replacement of the following type of template variables within the logging search query:
- Template variables generated from the OCI logs datasource
- Custom template variables
- Template variables generated from another datasource

### Caveats

1. While the generation of the compartment template variables using the `compartments()` query provides the correct compartment names, the use of the compartment template variable within the logging search query still does NOT work. That issue will be addressed in a future update.
2. At this time the logging datasource template variables will only support having a single value selected per template variable. Support for having multiple values selected or all values selected will be addressed in a future update.

### Testing

These changes were tested on the following platforms and browser combinations:
- MacOS & Chrome
- Linux & Chrome
- Linux & Firefox

### Test Process

To test the use of template variables in a data panel using the OCI Logging datasource plugin, perform the following steps:

1. Create new dashboard (or select an existing dashboard with no template variables)
2. Click the Dashboard Settings icon as shown in the following figure:
* TemplateVar-1-NewDashboard-Settings
3. On the Dashboard Settings page, click Variables in the left hand navigation pane as shown in the following figure:
* TemplateVar-2-DashboardSettings
4. On the Variables screen, click the 'Add variable' button as shown in the following figure:
* TemplateVar-4-AddVariable
5. Create a region template variable, filling in the template variable form as shown in the following figure. When the template variable information has been entered, click Variables in the 'Variables > Edit' heading
* TemplateVar-5-regionVar
6. On the Variables screen, click the New button as shown in the following figure:
* TemplateVar-6-NewVar
7.  Create a compartment template variable, filling in the template variable form as shown in the following figure. When the template variable information has been entered, click Variables in the 'Variables > Edit' heading:
*  TemplateVar-7-CompartmentsVar
8. On the Variables screen, click the New button.
9. Create a custom template variable, filling in the template variable form similar to as shown in the following figure. Note for the custom template variable you will need to provide values that correspond to values of a field in log records you can search.
* TemplateVar-8-CustomVar
10. The variables page should now look similar to the following figure:
* TemplateVar-9-ResultingVars
11. Click the 'Go Back' arrow at the upper left hand corner of the window
12. Select appropriate values for the template variables at the top of the dashboard window
13. Click the 'Add a new panel' box on the New Dashboard window as shown in the following figure:
* TemplateVar-10-NewPanel
14. On the data panel edit window,
* Change the datasource dropdown to the Oracle Cloud Infrastructure Logs datasource
* Click the Region dropdown selector within the data panel editor and select the `$region` option 
* Enter the OCI Logging search query string in the Query box including the use of one of the template variables within the query string. In the example in the figure below, $namespace is used in the query string as a placeholder for the name of the namespace for which log records should be filtered
* Click outside the Query box and data should be rendered for the data panel
* An example of a completed data panel is shown in the following figure:
* TemplateVar-11-QueryUsingTemplateVar

### CODE REVIEW

**Comment by doubleUTF** [comment]
@huskerdhf would you please provide an example how to validate this change? I.e. steps to use template variable in logs plugin, screenshots, etc.

**Comment by huskerdhf** [comment]
> @huskerdhf would you please provide an example how to validate this change? I.e. steps to use template variable in logs plugin, screenshots, etc.



> @huskerdhf would you please provide an example how to validate this change? I.e. steps to use template variable in logs plugin, screenshots, etc.

@doubleUTF Updated the PR description to include steps for testing the updates for this PR.

**Review by nagarnar — APPROVED** [review]
LGTM

**Comment by doubleUTF** [comment]
LGTM

**Review by doubleUTF — APPROVED** [review]

**Pull request merged**
