### PR TITLE
Fix log presentation

### PR DESCRIPTION
**Pull request by huskerdhf**
### Overview of Changes
This PR includes a number of significant changes to the plugin which are grouped into two different commits where the changes for each commit can be summarized as:

1. 'Remove unused/dead code' commit
- Removed numerous code artifacts that clearly were simply copied over from the metrics plugin but which had no bearing on the behavior, operation, or function of the logs plugin.
- Numerous files were touched as part of this code cleanup with most if not all of the JavaScript files being modified as well as the datasource.go file.
- Other than the src/datasource.js file, all other JavaScript files were only modified as part of this commit.
2. 'Add logic to build data frames from returned log search data' commit
- This commit contains a number of significant changes which are as follows
- Updated plugin backend to determine whether the user specified logging search query will return log records (e.g. a simple search of logs in a compartment) or will return metrics derived from log records (e.g. a logging search query that uses the `avg()`, `sum()`, `count()`, `min()`, or `max()` query functions).
- If the logging search query returns log records, i.e. does NOT use any of the mathematical query functions, then the plugin backend parses out the fields in the `logContent` element of each log record and builds a data frame with all of the extracted data where each "row" of the data frame corresponds to a returned log record.
- If the logging search query returns metrics derived from logs, i.e. the query DOES use one of the mathematical query functions, then the plugin backend parses the returned values and effectively constructs a single "row" for the data frame where each field of the data frame corresponds to the different returned results. For example, if the logging search query were of the form:  `search "<Compartment OCID>" | where substr(data.namespace, 0, 5) = 'cne-i' | summarize count (data.podname) by (data.namespace)` then there would be a separate field for each `data.namespace` value referenced in the logging search query results.
- Since a logging search query that returns metrics derived from logs effectively only has a single data point, to make it so that the query returns a time series of data, the plugin backend splits up the specified time range into a number of equal intervals and performs the specified logging search query over each of those intervals and combines the resulting data into a series of "rows" within the constructed data frame where each "row" represents the data for one interval and the timestamp for the "row" is the end timestamp for the interval.
- The plugin frontend now passes to the plugin backend the maximum number of data points value that a user can modify within the query options element of a data panel. The plugin backend checks this value to derive the number of intervals over which to perform the specified query ensuring that the number of data points does not exceed 10 and is no smaller than 2.
- The plugin backend now always parses the data returned by a logging search query into data frames, no matter whether the data is log records or metrics derived from log records, that are passed to the plugin frontend rather than dumping the logging search query results JSON blob into a single data field that is then parsed and interpreted by the plugin frontend.
- For logging search queries that return log records, the plugin logic no longer tries to derive log record fields which don't otherwise exist in the log records, such as `status`, and instead simply parses the log records into the top level elements under the logContent element of each log record. For example this common includes fields such `id`,`type`, `source`, `oracle`, `data`, etc. A user can utilize the Grafana transformation feature to parse additional fields out of the `data` element of the log records.
- The compartments() template variable logic was updated so the compartments() function actually returns a list of compartments.

### Other Notes
One other positive side effect of these changes is that now when a user selects the logging plugin in the Explore window of Grafana, the user can actually perform a logging search query and have the results properly displayed in the Explore window. This includes whether the user specifies a logging search query that returns log records or one that returns metrics. This is likely because the logs datasource plugin backend now returns data frames which can be directly understood by Grafana.

### Example Screenshots
Some example Grafana screen grabs when this version of the plugin was used include:
- Explore window with returned log records visualized
LogsExplore-LogRecords-Edited

- Explore window with log-based metrics visualized
LogsExplore-LogMetrics-Edited

- Dashboard with data panels showing Audit and custom (K8s container) logs for the specified time period
LogRecordsDashboard

- Dashboard row showing the use of the various Grafana time series related data panels showing the data returned for the `avg()`, `sum()`, `count()`, `min()`, or `max()` query functions
LogMetrics-TimeSeriesPanels
LogMetrics-TimeSeriesDataPanelEditor-Edited
LogMetrics-BarChartPanels
LogMetrics-StatPanels
LogMetrics-GaugePanels
LogMetrics-BarGaugePanels
LogMetrics-HeatMapPanels

**NOTE**: The data presented in the above panel screenshots isn't meant to be overly meaningful but simply reflect that the oci-grafana-logs plugin with these changes is returning time series data that can be directly visualized by Grafana.

- Dashboard containing a data panel with multiple logging search queries that return metric data
LogMetrics-TimeSeries-MultipleQueriesPerPanel

@nagarnar @doubleUTF

### CODE REVIEW

**Comment by nagarnar** [comment]
Would be good to update the copyright year to 2022 at least on the files touched in this PR

**Comment by huskerdhf** [comment]
Branch has been rebased after the small PRs for using mage for building the plugin and the regions list were merged

**Comment by huskerdhf** [comment]
> Would be good to update the copyright year to 2022 at least on the files touched in this PR

Has been addressed in updates on the branch

**Review by nagarnar — APPROVED** [review]
LGTM

**Pull request merged**
